packages:
- .
resolver: nightly-2017-12-18
extra-deps:
- git: https://github.com/sjakobi/hs-gauge
  commit: b5ad388ccecc23885c10aa77ac1c05d884c37127
- basement-0.0.4
- code-page-0.1.3
- math-functions-0.2.1.0
